// prisma/seed.ts
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const medicines = [
  {
    name: 'Aciclovir / Medskin Clovir',
    strength: '400mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Aciclovir bôi ngoài da',
    strength: '5%',
    frequency: '',
    instructions: '',
    units: 'tuýp',
  },
  {
    name: 'Amoxicillin',
    strength: '500mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Protamol / Agiprofen',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Alphachymotrypsin',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Spacmarizine',
    strength: '40mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Acetylcystein',
    strength: '200mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Vitamin C',
    strength: '500mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Folic-Fe / Agifivit',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Bromhexin (Bixovom)',
    strength: '8mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Cephalexin',
    strength: '500mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Coldacmin',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Chlorpheniramin',
    strength: '4mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Cetirizin',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Cinnarizin',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Calcium Hasan',
    strength: '500mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Vitamin C sủi',
    strength: '1000mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Calci D',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Carbomango',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Cimetidin',
    strength: '300mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Ciprofloxacin (Vidiphar)',
    strength: '0.3% / 5ml',
    frequency: '',
    instructions: '',
    units: 'chai',
  },
  {
    name: 'Domitazol',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Diclofenac',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Decontapp Pharco',
    strength: '250mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Dextromethorphan / Vacotexphan',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Domperidon (Mutecium-M)',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Erythromycin (VDP)',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Eugica Fort',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Enpovid AD',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Gikanin / Tangynyl',
    strength: '500mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Phosphalugel',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'gói',
  },
  {
    name: 'Hapacol',
    strength: '650mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Levoogi',
    strength: '5mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Loperamid',
    strength: '2mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Neocin',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'chai',
  },
  {
    name: 'Methylprednisolon',
    strength: '16mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Metronidazol',
    strength: '250mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Meloxicam',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Mekocoramin',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Magnesi B6',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Ovac (Omeprazol)',
    strength: '20mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Oresol Baby',
    strength: '4.1g',
    frequency: '',
    instructions: '',
    units: 'gói',
  },
  {
    name: 'Prednisolon',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Paracetamol',
    strength: '500mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Piracetam',
    strength: '800mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Biolac',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Smecta',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'gói',
  },
  {
    name: 'Sorbitol',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'gói',
  },
  {
    name: 'Terpin-Codein / Terpinzoat',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Theralene / Toussolene',
    strength: '5mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Tyrotab / Pasitussin',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Vitamin PP',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Vitamin B1-B6-B12',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Vitamin B1',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Hoạt huyết DN',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Amlodipin',
    strength: '5mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Panadol',
    strength: '500mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Cefuroxim',
    strength: '500mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Ciprofloxacin',
    strength: '500mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Cefixim',
    strength: '200mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Captopril',
    strength: '25mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Griseofulvin bôi ngoài da',
    strength: '5%',
    frequency: '',
    instructions: '',
    units: 'tuýp',
  },
  {
    name: 'Tenoxicam',
    strength: '20mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Loravidi (Loratadin)',
    strength: '10mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Polydesone',
    strength: '5ml',
    frequency: '',
    instructions: '',
    units: 'chai',
  },
  {
    name: 'Gentamycin',
    strength: '0.3% / 5ml',
    frequency: '',
    instructions: '',
    units: 'chai',
  },
  {
    name: 'Natri Clorid 0.9%',
    strength: '10ml',
    frequency: '',
    instructions: '',
    units: 'chai',
  },
  {
    name: 'Biosubtyl-II',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'gói',
  },
  {
    name: 'Silkeron',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'tuýp',
  },
  {
    name: 'Efferalgan',
    strength: '500mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Klamentin',
    strength: '1g',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Zaromax',
    strength: '500mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Celecoxib',
    strength: '200mg',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Dinalvic VPC',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
  {
    name: 'Nidal',
    strength: '',
    frequency: '',
    instructions: '',
    units: 'viên',
  },
];

async function main() {
  for (const med of medicines) {
    await prisma.medicine.upsert({
      where: { name: med.name },
      update: {
        strength: med.strength,
        frequency: med.frequency,
        instructions: med.instructions,
        units: med.units,
        isActive: true,
      },
      create: med,
    });
  }
  console.log(
    `✅ Seeded ${medicines.length} medicines (frequency & instructions set to "" where unknown).`,
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
